### PR TITLE
Add Apache 2.0 license support

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by hackebrot** [comment]
Hey @s0undt3ch, thank you for submitting a PR.

I think ecd8701 broke your PR. The ``license`` variable needs to match 100%.

Please also update ``setup.py`` to support the new license. :bow:

**Comment by s0undt3ch** [comment]
Yeah, forgot to update he match. Will updated.

**Comment by s0undt3ch** [comment]
I think I've updated everything you requested, please let me know if there's something else missing.

**Comment by hackebrot** [comment]
:+1:

**Comment by s0undt3ch** [comment]
Awesome!

**Comment by hackebrot** [comment]
Thank you :bow:

**Pull request merged**
